require('plugins')
require('sets')
require('bindings')
require('nvim-autopairs').setup()
require('nvim-treesitter').setup()
require('nvim_comment').setup()
require('nv-compe')
require('nv-tree')
require('autocmds')
require('nv-material')

require('lsps')
