require('plugins')
require('sets')
require('bindings')
require('nv-compe')
require('nv-tree')
require('nv-colorizer')
require('autocmds')
require('nv-material')
require('nv-colorizer')

require('nvim-autopairs').setup()
require('nvim-treesitter').setup()
require('nvim_comment').setup()

require('lsps')
