require('plugins')
require('sets')
require('bindings')
require('autocmds')
require('nv-colorizer')
require('nv-compe')
require('nv-tree')
require('nv-autopairs')
require("nv-treesitter")
require('nvim_comment').setup()
require('lsps')
vim.o.background = "dark"
vim.cmd([[colorscheme spacegray]])
