Core.load_module('plugins/general')
Core.load_module('plugins/snacks')
Core.load_module('plugins/tools_lsp')
Core.load_module('plugins/completion')
Core.load_module('plugins/conform')
Core.load_module('plugins/ui')
Core.load_module('plugins/ai')
